import type { NoteRecord } from "../db/repositories/notes";

export function mapNoteSummary(note: Partial<NoteRecord>, categoryIds: string[]) {
  return {
    id: note.id ?? "",
    title: note.title ?? "",
    slug: note.slug ?? "",
    excerpt: note.excerpt ?? "",
    outlineMd: note.outline_md ?? "",
    seoTitle: note.seo_title ?? "",
    seoDescription: note.seo_description ?? "",
    seoKeywords: note.seo_keywords ?? "",
    ogTitle: note.og_title ?? "",
    ogDescription: note.og_description ?? "",
    ogImageAssetId: note.og_image_asset_id ?? null,
    ogImageGeneratedAt: note.og_image_generated_at ?? null,
    categoryIds,
    status: note.status ?? "draft",
    publishAt: note.publish_at ?? null,
    sanityDocumentId: note.sanity_document_id ?? null,
    sanityRevision: note.sanity_revision ?? null,
    lastError: note.last_error ?? null,
    aiRewriteContentMd: note.ai_rewrite_content_md ?? null,
    aiRewriteExcerpt: note.ai_rewrite_excerpt ?? null,
    aiRewriteSeoTitle: note.ai_rewrite_seo_title ?? null,
    aiRewriteSeoDescription: note.ai_rewrite_seo_description ?? null,
    aiRewriteSeoKeywords: note.ai_rewrite_seo_keywords ?? null,
    aiRewriteOgTitle: note.ai_rewrite_og_title ?? null,
    aiRewriteOgDescription: note.ai_rewrite_og_description ?? null,
    aiRewriteUpdatedAt: note.ai_rewrite_updated_at ?? null,
    createdAt: note.created_at ?? null,
    updatedAt: note.updated_at ?? null,
  };
}

export function mapNoteDetail(note: NoteRecord, categoryIds: string[]) {
  return {
    id: note.id,
    title: note.title,
    slug: note.slug,
    contentMd: note.content_md,
    outlineMd: note.outline_md,
    excerpt: note.excerpt ?? "",
    seoTitle: note.seo_title ?? "",
    seoDescription: note.seo_description ?? "",
    seoKeywords: note.seo_keywords ?? "",
    ogTitle: note.og_title ?? "",
    ogDescription: note.og_description ?? "",
    ogImageAssetId: note.og_image_asset_id,
    categoryIds,
    status: note.status,
    publishAt: note.publish_at,
    sanityDocumentId: note.sanity_document_id,
    sanityRevision: note.sanity_revision,
    lastError: note.last_error,
    aiRewriteContentMd: note.ai_rewrite_content_md,
    aiRewriteExcerpt: note.ai_rewrite_excerpt,
    aiRewriteSeoTitle: note.ai_rewrite_seo_title,
    aiRewriteSeoDescription: note.ai_rewrite_seo_description,
    aiRewriteSeoKeywords: note.ai_rewrite_seo_keywords,
    aiRewriteOgTitle: note.ai_rewrite_og_title,
    aiRewriteOgDescription: note.ai_rewrite_og_description,
    aiRewriteUpdatedAt: note.ai_rewrite_updated_at,
    createdAt: note.created_at,
    updatedAt: note.updated_at,
  };
}
