export type AiPromptPreset = {
  name: string;
  description: string;
  outlinePrompt: string;
  contentPrompt: string;
};

export const AI_PROMPT_PRESETS: AiPromptPreset[] = [
  {
    name: "Blog SEO Marketing",
    description:
      "Artikel blog marketing berbahasa Indonesia untuk konten edukatif, thought leadership, dan SEO organik. Cocok untuk topik industri, tips bisnis, dan panduan strategis.",
    outlinePrompt:
      "Buat outline artikel blog SEO berbahasa Indonesia untuk audiens B2B profesional.\n\nAlur pembaca (PAS):\n1. Hook + Problem — masuk ke masalah pembaca dengan pertanyaan retoris atau pernyataan masalah spesifik\n2. Agitate — perbesar urgensi: biaya, waktu, peluang yang hilang\n3. Evaluasi & Solusi — kriteria, pendekatan, langkah konkret\n4. Trust — bukti, FAQ, objection handling\n5. CTA — langkah selanjutnya\n\nAturan heading:\n- H2/H3 yang menjanjikan nilai spesifik\n- Rumus: Outcome ('Cara Memangkas Biaya IT 30%'), Problem ('Kenapa Proyek IT Sering Gagal?'), Numbered ('7 Tanda Bisnis Anda Butuh Upgrade Sistem'), Contrast ('In-House vs Outsourcing: Mana yang Lebih Efisien?')\n- JANGAN: 'Pendahuluan', 'Kesimpulan', 'Informasi Tambahan'\n\nSection wajib:\n- Konteks masalah (PAS framework)\n- Insight atau data pendukung (tanpa mengarang angka)\n- Langkah atau rekomendasi praktis\n- FAQ 3-5 pertanyaan nyata calon pembeli (jawaban spesifik, bukan diplomatis)\n- CTA penutup\n\nSetiap heading harus punya catatan 1 kalimat tentang isinya. 'Earn its place': jika heading bisa dihapus tanpa merusak alur, hapus.",
    contentPrompt:
      "Kembangkan outline menjadi artikel blog marketing B2B berbahasa Indonesia.\n\nPembuka (PAS):\n- Problem: sebutkan masalah spesifik pembaca ('Website Anda loading lebih dari 3 detik?')\n- Agitate: perbesar dampaknya ('Setiap detik tambahan = 7% pengunjung pergi')\n- Solution: janji jawaban artikel ini\n- JANGAN mulai dengan definisi umum atau 'Di era digital saat ini'\n- Tulis langsung ke pembaca menggunakan 'Anda'\n\nStruktur:\n- Jawab intent utama di 30% pertama artikel\n- Section manfaat: Benefit Block (headline hasil → penjelasan → bukti/skenario)\n- Section langkah: numbered list (aksi + hasil)\n- Gunakan pertanyaan retoris untuk re-engage pembaca di awal section baru\n- Analogi untuk konsep teknis\n\nScannability:\n- Paragraf pendek (3-4 kalimat), bold 1-2 frasa kunci per section\n- Bullet/numbered list untuk 3+ item, subheading setiap 3-4 paragraf\n\nKualitas:\n- Spesifik: 'memangkas waktu dari 4 jam jadi 15 menit' bukan 'meningkatkan efisiensi'\n- Show don't tell, akui trade-off dan batasan\n- Bahasa 'Anda', aktif, percaya diri\n\nTransisi: variasikan (kontras, sebab-akibat, contoh, pertanyaan). JANGAN: 'Selanjutnya kita akan membahas', 'Perlu dicatat bahwa', 'Pada intinya'\n\nCTA: benefit-driven ('Konsultasi Gratis tentang Kebutuhan IT Anda' bukan 'Hubungi Kami')\n\nMetadata: isi semua field koheren. OG title/description harus berbeda dari SEO (sesuaikan konteks sosial WhatsApp/LinkedIn).\n\nSelf-review: (1) frasa AI blacklist? (2) heading generik? (3) mudah di-scan? (4) transisi bervariasi? (5) CTA benefit-driven?\n\nLarangan: klaim bombastis, statistik mengarang, kalimat generik, tanda seru di body.",
  },
  {
    name: "Review Produk & Afiliasi",
    description:
      "Artikel review produk atau layanan dengan sudut pandang evaluatif, cocok untuk konten afiliasi dan perbandingan produk. Menekankan kriteria penilaian jujur dan CTA konversi.",
    outlinePrompt:
      "Buat outline artikel review produk/layanan berbahasa Indonesia untuk audiens B2B yang sedang mengevaluasi solusi.\n\nAlur pembaca:\n1. Hook — siapa yang cocok dan kenapa review ini penting\n2. Overview singkat — apa produknya, untuk siapa, positioning\n3. Kriteria evaluasi — apa yang dinilai dan kenapa kriteria ini penting\n4. Penilaian per aspek — kelebihan dan kekurangan jujur per kriteria\n5. Perbandingan singkat — alternatif yang perlu dipertimbangkan\n6. Verdict — siapa yang cocok, siapa yang sebaiknya pilih alternatif\n7. FAQ — pertanyaan nyata sebelum membeli\n8. CTA — link atau langkah selanjutnya\n\nAturan heading:\n- Spesifik dan evaluatif: 'Performa Under Load: Cukup untuk UMKM, Kurang untuk Enterprise', 'Harga vs Value: Worth It untuk Tim 5-20 Orang'\n- JANGAN: 'Kelebihan', 'Kekurangan' (terlalu generik tanpa konteks)\n\nSection wajib:\n- Ringkasan cepat (siapa yang cocok dalam 1 kalimat)\n- Kriteria evaluasi dengan penjelasan kenapa penting\n- Penilaian per aspek dengan bukti/skenario penggunaan\n- Alternatif dan kapan harus pertimbangkan alternatif\n- FAQ 3-5 pertanyaan pembeli\n- Verdict jelas dengan segmentasi audiens\n\nSetiap heading punya catatan 1 kalimat. 'Earn its place': hapus section yang tidak membantu keputusan pembelian.",
    contentPrompt:
      "Kembangkan outline menjadi artikel review produk/layanan berbahasa Indonesia.\n\nPembuka:\n- Langsung jawab: produk ini untuk siapa? 'Jika Anda mencari [solusi] untuk [konteks], [produk] layak dipertimbangkan — tapi bukan untuk semua orang.'\n- Berikan verdict singkat di 2 paragraf pertama (jangan bury the lead)\n- Tulis ke pembaca menggunakan 'Anda'\n\nStruktur review:\n- Setiap aspek yang dinilai: klaim → bukti/skenario → penilaian jujur\n- Sebutkan kelebihan DAN kekurangan secara seimbang\n- Kekurangan harus spesifik: bukan 'kurang cocok untuk beberapa pengguna' tapi 'tidak mendukung multi-currency, jadi tidak cocok untuk bisnis ekspor-impor'\n- Bandingkan dengan alternatif secara objektif, bukan memihak\n\nTrust builder:\n- Jelaskan kriteria penilaian dan kenapa penting\n- Gunakan skenario penggunaan nyata: 'Saat tim kami mencoba fitur X untuk project dengan 50 user...'\n- Akui batasan review (jika tidak bisa test semua fitur)\n\nScannability:\n- Rating/verdict per section (misal: 'Cocok untuk: tim kecil 5-20 orang')\n- Bold kriteria kunci, bullet untuk daftar fitur\n- Tabel perbandingan jika ada 2+ alternatif\n\nCTA:\n- CTA utama: arahkan ke langkah pembelian atau trial ('Coba Gratis 14 Hari', 'Lihat Harga untuk Tim Anda')\n- CTA sekunder: bandingkan dengan alternatif ('Bandingkan dengan [Produk Lain]')\n- Tempatkan CTA setelah verdict positif, bukan di tengah kritik\n\nMetadata: SEO title fokus keyword produk + 'review'. OG title lebih curiosity-driven ('Kami Test [Produk] Selama 2 Minggu — Ini Hasilnya').\n\nSelf-review: (1) review seimbang (ada pro dan kontra)? (2) kriteria jelas? (3) verdict segmentasi audiens? (4) CTA di tempat yang tepat?\n\nLarangan: klaim palsu tentang produk, statistik mengarang, review yang terasa seperti iklan.",
  },
  {
    name: "How-To & Tutorial",
    description:
      "Artikel panduan langkah demi langkah untuk menyelesaikan masalah teknis atau bisnis. Struktur numbered steps, mudah diikuti, dengan tips dan jebakan di setiap tahap.",
    outlinePrompt:
      "Buat outline artikel how-to/tutorial berbahasa Indonesia untuk audiens B2B profesional.\n\nAlur pembaca:\n1. Hook + Problem — kenapa pembaca perlu melakukan ini? Masalah apa yang diselesaikan?\n2. Prasyarat — apa yang dibutuhkan sebelum mulai (tools, akses, pengetahuan)\n3. Langkah-langkah utama — 5-10 langkah bernomor, setiap langkah punya fungsi jelas\n4. Tips dan jebakan — apa yang sering salah di setiap tahap?\n5. Hasil yang diharapkan — apa yang pembaca capai setelah mengikuti semua langkah\n6. Langkah selanjutnya — apa yang bisa dilakukan setelah tutorial ini\n7. FAQ — pertanyaan yang muncul saat mempraktikkan\n\nAturan heading:\n- Setiap langkah: 'Langkah [N]: [Aksi Spesifik] — [Hasil yang Didapat]'\n- Contoh: 'Langkah 3: Backup Database Sebelum Migrasi — Mencegah Kehilangan Data'\n- JANGAN: 'Langkah 1', 'Langkah 2' tanpa penjelasan aksi\n\nSection wajib:\n- Ringkasan: apa yang akan dicapai, berapa estimasi waktu, level kesulitan\n- Prasyarat yang jelas\n- Langkah-langkah detail dengan tips per langkah\n- Troubleshooting: 3-5 masalah umum dan solusinya\n- FAQ 3-5 pertanyaan praktisi\n- CTA: arahkan ke bantuan profesional jika tutorial terlalu kompleks\n\nSetiap langkah punya catatan 1 kalimat tentang apa yang dilakukan dan kenapa. Urutan langkah harus logis dan tidak bisa diacak.",
    contentPrompt:
      "Kembangkan outline menjadi artikel how-to/tutorial berbahasa Indonesia.\n\nPembuka:\n- Langsung sebutkan: apa yang akan pembaca capai, estimasi waktu, dan level kesulitan\n- Contoh: 'Dalam panduan ini, Anda akan memigrasi database dari MySQL ke PostgreSQL dalam 7 langkah. Estimasi waktu: 2-4 jam tergantung ukuran data. Level: menengah.'\n- Tulis ke pembaca menggunakan 'Anda'\n\nStruktur langkah:\n- Setiap langkah: aksi → penjelasan kenapa → tips → jebakan yang perlu dihindari\n- Gunakan numbered list untuk langkah utama\n- Sertakan output yang diharapkan setelah setiap langkah ('Setelah langkah ini, Anda akan melihat...')\n- Jika langkah kompleks, pecah jadi sub-langkah\n\nTips dan jebakan:\n- Setiap langkah harus punya minimal 1 tip atau warning\n- Tip: 'Untuk database di atas 10GB, gunakan --chunk-size=1000 agar tidak timeout'\n- Warning: 'Jangan skip langkah backup — jika migrasi gagal tanpa backup, data Anda hilang permanen'\n\nScannability:\n- Bold nama tool, command, atau parameter penting\n- Code block untuk command atau konfigurasi\n- Screenshot placeholder jika perlu (tandai dengan [screenshot: deskripsi])\n- Bullet untuk checklist prasyarat\n\nTroubleshooting:\n- Format: 'Masalah: [deskripsi] → Solusi: [langkah]'\n- 3-5 masalah paling umum yang dihadapi praktisi\n\nCTA:\n- Jika tutorial kompleks: 'Butuh bantuan implementasi? Diskusikan dengan tim kami'\n- Jika sederhana: 'Setelah selesai, lanjutkan ke [tutorial terkait]'\n\nMetadata: SEO title fokus keyword 'cara' atau 'panduan' + topik. OG title fokus hasil ('Cara Setup Server dalam 30 Menit — Panduan Lengkap').\n\nSelf-review: (1) urutan langkah logis? (2) setiap langkah punya tip/warning? (3) output per langkah jelas? (4) troubleshooting cukup?\n\nLarangan: langkah yang skip konteks, asumsi pembaca sudah tahu tanpa menjelaskan, command tanpa penjelasan.",
  },
  {
    name: "Listicle & Tips",
    description:
      "Artikel list (tips, kesalahan, tools, strategi) dengan format scannable dan punchy. Cocok untuk konten social-friendly dan featured snippet.",
    outlinePrompt:
      "Buat outline artikel listicle berbahasa Indonesia untuk audiens B2B profesional.\n\nAlur pembaca:\n1. Hook — kenapa list ini penting? Masalah apa yang diselesaikan?\n2. List items — 5-15 item, setiap item berdiri sendiri tapi saling terkait tema\n3. Ringkasan / prioritas — item mana yang paling berdampak?\n4. CTA — langkah selanjutnya\n\nAturan heading:\n- Title: angka spesifik + outcome ('9 Kesalahan SEO yang Membuat Traffic Turun 40%')\n- Setiap item heading: menjanjikan value spesifik\n- Contoh: '#3: Mengabaikan Core Web Vitals — Penyebab #1 Penurunan Ranking di 2025'\n- JANGAN: 'Tips 1', 'Poin 2' tanpa konteks\n\nStruktur per item:\n- Heading yang spesifik dan scannable\n- Catatan 1 kalimat: apa masalahnya dan kenapa penting\n\nSection wajib:\n- Pembuka yang menjelaskan kenapa jumlah item ini dipilih\n- List items (urutkan dari paling impactful ke least, atau dari paling mudah ke paling sulit)\n- Quick wins section: 2-3 item yang bisa langsung diterapkan hari ini\n- FAQ 3-5 pertanyaan terkait\n- CTA penutup\n\n'Earn its place': setiap item harus punya insight unik. Jika 2 item bisa digabung tanpa kehilangan nilai, gabungkan.",
    contentPrompt:
      "Kembangkan outline menjadi artikel listicle berbahasa Indonesia.\n\nPembuka:\n- Langsung masuk ke masalah: 'Anda sudah optimasi konten, tapi traffic tetap turun? Kemungkinan besar salah satu dari 9 kesalahan ini yang jadi penyebab.'\n- Sebutkan berapa item dan kenapa angka ini dipilih\n- Tulis ke pembaca menggunakan 'Anda'\n\nStruktur per item:\n- Heading: nama masalah/tip/strategi\n- Paragraf 1: apa masalahnya dan kenapa penting (2-3 kalimat)\n- Paragraf 2: dampak konkret jika diabaikan ('Bisa menurunkan traffic hingga 40% dalam 3 bulan')\n- Paragraf 3: cara memperbaiki atau menerapkan (langkah konkret)\n- Opsional: contoh atau analogi\n\nScannability (KRITIS untuk listicle):\n- Bold nama tip/masalah di setiap heading\n- Ringkasan 1 kalimat di awal setiap item (readers scan dulu, baca detail kemudian)\n- Bullet list di dalam item jika ada 3+ sub-poin\n- Paragraf pendek (2-3 kalimat per paragraf)\n\nQuick Wins:\n- Setelah semua item, berikan section 'Mulai dari Sini' yang merangkum 2-3 item paling mudah diterapkan\n- Format: checklist yang bisa langsung dicentang\n\nKualitas:\n- Setiap item harus berdiri sendiri (pembaca bisa baca item #5 tanpa baca #1-4)\n- Tapi tetap saling terkait tema besar\n- Hindari pengulangan insight antar item\n\nCTA: 'Sudah coba tip #[N]? Konsultasikan strategi SEO lengkap Anda bersama tim kami.'\n\nMetadata: SEO title HARUS mengandung angka ('7 Tips...', '10 Kesalahan...'). OG title lebih curiosity-driven ('Kesalahan #4 Adalah yang Paling Sering Dilakukan — Cek Apakah Anda Juga').\n\nSelf-review: (1) setiap item punya insight unik? (2) mudah di-scan per item? (3) ada quick wins section? (4) tidak ada pengulangan antar item?\n\nLarangan: item yang hanya填充 kata tanpa insight, angka yang dipaksakan (jangan tulis 15 jika hanya ada 8 insight berkualitas).",
  },
  {
    name: "Perbandingan & Versus",
    description:
      "Artikel perbandingan dua atau lebih produk, pendekatan, atau strategi. Objektif, terstruktur, dengan kriteria evaluasi jelas dan rekomendasi segmentasi.",
    outlinePrompt:
      "Buat outline artikel perbandingan/versus berbahasa Indonesia untuk audiens B2B yang sedang mengevaluasi pilihan.\n\nAlur pembaca:\n1. Hook — kenapa perbandingan ini penting? Situasi apa yang membuat pembaca perlu memilih?\n2. Overview singkat — profil masing-masing opsi (1-2 kalimat per opsi)\n3. Kriteria perbandingan — apa yang dinilai dan kenapa\n4. Perbandingan per kriteria — head-to-head per aspek\n5. Ringkasan tabel — overview cepat semua kriteria\n6. Rekomendasi segmentasi — siapa cocok pakai apa\n7. FAQ — pertanyaan sebelum memutuskan\n8. CTA — bantuan memilih atau langkah selanjutnya\n\nAturan heading:\n- Per kriteria: 'Performa: [Opsi A] Lebih Cepat, Tapi [Opsi B] Lebih Stabil'\n- Rekomendasi: '[Opsi A] untuk [Konteks A], [Opsi B] untuk [Konteks B]'\n- JANGAN: 'Kelebihan A', 'Kekurangan A' (terlalu generik)\n\nSection wajib:\n- Ringkasan cepat: siapa menang di kriteria apa (1 tabel atau ringkasan)\n- Kriteria evaluasi dengan penjelasan kenapa penting\n- Perbandingan head-to-head per kriteria (seimbang, tidak memihak)\n- Tabel ringkasan semua kriteria\n- Rekomendasi berdasarkan segmentasi (ukuran bisnis, budget, kebutuhan teknis)\n- FAQ 3-5 pertanyaan evaluator\n- CTA: bantuan konsultasi pemilihan\n\nSetiap kriteria harus dinilai dari kedua sisi. Tidak ada pemenang mutlak — selalu ada konteks di mana satu opsi lebih baik.",
    contentPrompt:
      "Kembangkan outline menjadi artikel perbandingan/versus berbahasa Indonesia.\n\nPembuka:\n- Langsung jawab: 'Memilih antara [A] dan [B]? Jawabannya tergantung [faktor kunci].' Jangan mulai dengan definisi produk.\n- Berikan quick verdict: siapa menang di area apa (jangan bury the lead)\n- Tulis ke pembaca menggunakan 'Anda'\n\nStruktur perbandingan:\n- Setiap kriteria: konteks kenapa penting → penilaian A → penilaian B → verdict per kriteria\n- Seimbang dan objektif: setiap opsi harus punya kelebihan dan kekurangan\n- Gunakan skenario penggunaan: 'Untuk tim 5 orang dengan budget terbatas, [A] lebih masuk akal karena...'\n- Akui bias jika ada ('Kami lebih sering menggunakan [A] untuk klien enterprise, tapi ini berdasarkan pengalaman kami')\n\nTabel ringkasan:\n- Buat tabel perbandingan markdown dengan kriteria sebagai baris dan opsi sebagai kolom\n- Gunakan rating kualitatif ('Cocok untuk enterprise', 'Lebih baik untuk startup') bukan angka tanpa dasar\n\nRekomendasi segmentasi:\n- Format: 'Pilih [A] jika: [kondisi 1], [kondisi 2]'\n- 'Pilih [B] jika: [kondisi 1], [kondisi 2]'\n- 'Pertimbangkan [C/alternatif] jika: [kondisi]'\n- Minimal 3 segmen audiens\n\nScannability:\n- Bold nama opsi di setiap perbandingan\n- Tabel untuk ringkasan cepat\n- Bullet untuk daftar kriteria\n\nCTA: 'Masih bingung memilih? Ceritakan kebutuhan bisnis Anda dan kami bantu rekomendasikan solusi yang tepat.'\n\nMetadata: SEO title: '[A] vs [B]: Perbandingan Lengkap [Tahun]'. OG title: '[A] vs [B] — Kami Test Keduanya, Ini Perbedaannya'.\n\nSelf-review: (1) perbandingan seimbang? (2) tabel ringkasan ada? (3) rekomendasi segmentasi minimal 3? (4) tidak ada pemenang mutlak tanpa konteks?\n\nLarangan: memihak satu opsi tanpa alasan, klaim yang tidak bisa diverifikasi, perbandingan yang terasa seperti iklan salah satu produk.",
  },
  {
    name: "Landing Page & Sales Content",
    description:
      "Konten untuk landing page atau halaman penjualan dengan framework direct response copywriting (PAS, AIDA). Fokus konversi, benefit-driven, dan CTA yang kuat.",
    outlinePrompt:
      "Buat outline konten landing page/sales page berbahasa Indonesia untuk audiens B2B.\n\nAlur pembaca (StoryBrand framework):\n1. Hero section — headline + subheadline + CTA utama (above the fold)\n2. Problem — masalah yang dihadapi pembaca (PAS: Problem-Agitate)\n3. Solution — bagaimana produk/layanan menyelesaikan masalah (PAS: Solution)\n4. Benefits — 3-5 manfaat utama dengan bukti\n5. How it works — 3-4 langkah sederhana\n6. Social proof — testimoni, angka, logo klien (hanya jika ada data valid)\n7. Comparison — kenapa berbeda dari alternatif/status quo\n8. Objection handling — FAQ yang menjawab keraguan\n9. Final CTA — ulangi CTA utama + risk reversal\n\nAturan heading:\n- Headline hero: outcome-focused, 6-12 kata ('Website Bisnis Online dalam 2 Minggu Tanpa Coding')\n- Section headings: benefit-driven, bukan feature-driven\n- Buruk: 'Fitur Kami', 'Tentang Layanan'. Baik: 'Fokus ke Bisnis Anda, Biar Kami yang Urus Teknis'\n\nSection wajib:\n- Hero: headline + subheadline + CTA\n- Problem section (PAS: agitate konsekuensi)\n- 3-5 benefit blocks (headline hasil + penjelasan + bukti)\n- How it works (3-4 langkah)\n- Objection handling FAQ (5-7 pertanyaan)\n- Final CTA dengan risk reversal\n\nSetiap section punya catatan 1 kalimat. Tidak semua section harus dipakai — sesuaikan dengan konteks produk/layanan.",
    contentPrompt:
      "Kembangkan outline menjadi konten landing page/sales page berbahasa Indonesia.\n\nHero Section (Above the Fold):\n- Headline: 6-12 kata, outcome-focused. Rumus: '[Hasil] tanpa [pain point]' atau '[Hasil] dalam [timeframe]'\n- Subheadline: 15-25 kata, jelaskan bagaimana ini mungkin\n- CTA utama: action verb + value ('Mulai Konsultasi Gratis', 'Lihat Demo Sekarang')\n- JANGAN: 'Selamat Datang di [Brand]' atau 'Solusi Terbaik untuk Bisnis Anda'\n\nProblem Section (PAS):\n- Problem: deskripsikan masalah pembaca lebih baik dari mereka bisa mendeskripsikannya sendiri\n- Agitate: perbesar konsekuensi — biaya tersembunyi, waktu terbuang, peluang hilang, frustrasi tim\n- Buat pembaca berpikir 'itu persis situasi saya'\n- Gunakan pertanyaan retoris: 'Sudah berapa kali Anda kehilangan pelanggan karena website yang lambat?'\n\nBenefits Section:\n- 3-5 benefit blocks (jangan lebih dari 5)\n- Setiap block: Headline hasil (outcome) + penjelasan cara kerja (1-2 kalimat) + bukti/skenario\n- Benefits bukan features: 'Kirim invoice dalam 30 detik' bukan 'Fitur invoice otomatis'\n\nHow It Works:\n- 3-4 langkah sederhana: action verb + outcome\n- Setiap langkah: '[Aksi] — [Hasil yang didapat]'\n- Kurangi kompleksitas yang dirasakan pembaca\n\nObjection Handling:\n- 5-7 FAQ yang menjawab keraguan nyata\n- Format: pertanyaan yang pembaca pikirkan tapi tidak berani tanyakan\n- Jawaban spesifik dan percaya diri, bukan diplomatis\n\nFinal CTA:\n- Ulangi CTA utama dengan konteks berbeda\n- Tambahkan risk reversal jika relevan ('Konsultasi gratis tanpa komitmen', 'Tidak perlu kartu kredit')\n- Urgency natural (bukan palsu): 'Jadwal konsultasi terbatas minggu ini'\n\nScannability:\n- Setiap section harus bisa dibaca dalam 10 detik\n- Bold benefit utama di setiap block\n- Short paragraphs (2-3 kalimat maksimal)\n- Whitespace generous\n\nTone: percaya diri tapi tidak agresif. Consultative, bukan hard-selling. Pembaca B2B menghargai kejujuran.\n\nMetadata: SEO title fokus keyword layanan + outcome. OG title fokus curiosity atau hasil ('Kenapa 50+ Bisnis di Surabaya Pilih Layanan Ini').\n\nSelf-review: (1) headline hero outcome-focused? (2) problem section bikin pembaca merasa dipahami? (3) benefits bukan features? (4) CTA jelas dan benefit-driven? (5) objection handling menjawab keraguan nyata?\n\nLarangan: klaim palsu, social proof mengarang, urgency palsu ('hanya hari ini!' padahal tidak), buzzwords tanpa substansi.",
  },
];
